### ISSUE TITLE
Preview Gii Error

### ISSUE THREAD

**Issue by RGTimothy** [mootensai/yii2-enhanced-gii#42] opened 2016-02-23 09:02 UTC
There is an error whenever I try to preview my crud (before I generate it) as these images below:

![gii2](https://cloud.githubusercontent.com/assets/3026828/13246523/b7586c12-da46-11e5-8059-bf97ea139265.PNG)

And here is the error:

![gii1](https://cloud.githubusercontent.com/assets/3026828/13246534/c9e49f54-da46-11e5-8149-f5af946ca1ee.PNG)

**Comment by mootensai** [comment] 2016-02-23 09:17
hmm.. I can't reproduce the error, which yii2 version are you using? The Schema object have `TYPE_DOUBLE` since 2.0 to 2.0.7

https://github.com/yiisoft/yii2/blob/master/framework/db/Schema.php

can you help me to find out what's wrong?

**Comment by RGTimothy** [comment] 2016-02-23 09:24
Actually I'm using 2.0.3 now. Hmm, ok then. Will let you know once I solved this issue.

**Comment by RGTimothy** [comment] 2016-02-23 09:29
I think my error somehow related to this [issue](https://github.com/yiisoft/yii2/issues/7490) 
Now I'm trying to update all of the dependencies things.

**Comment by mootensai** [comment] 2016-02-23 09:34
Alright then.. I think it's save to close this issue for now..

**Closed as completed by mootensai** 2016-02-23 09:34 UTC
