### ISSUE TITLE
Bug on Gii in form update related model - action update is deleting the default keys

### ISSUE THREAD

**Issue by alvarolordelo** [mootensai/yii2-enhanced-gii#91] opened 2016-11-29 03:43 UTC
after create the CRUD - and insert values the update action isn't performing well, 
see what happens if you press de update action and in the update view you confirm the update, even don't changing any values the action delete the values and re-insert in the table...it will produce new keys ID on those tables....and since they're related it will broke the app database...
![image](https://cloud.githubusercontent.com/assets/1663952/20695647/68e27746-b5cc-11e6-83f6-15d070e896c2.png)

before click on update button 
![image](https://cloud.githubusercontent.com/assets/1663952/20695672/8aced688-b5cc-11e6-8914-f041fe18e28f.png)

after click on update button
![image](https://cloud.githubusercontent.com/assets/1663952/20695684/a2785084-b5cc-11e6-8e02-ee7eba867e93.png)

There are other minor issues but this one is pretty seriously.
Thanks for the great work, after all that's the ninja gii.

**Comment by gvasilopulos** [comment] 2016-12-04 18:01
I can confirm this bug , but I think it has something to do with the "child" view file
I tested this against 2 related tables. regions with "child" cities. Whenever I update the child cities from the "parent" model this does happen under this specific condition
```php
echo TabularForm::widget([
    'dataProvider' => $dataProvider,
    'formName' => 'Cities',
    'checkboxColumn' => false,
    'actionColumn' => false,
    'attributeDefaults' => [
        'type' => TabularForm::INPUT_TEXT,
    ],
    'attributes' => [
        "city_id" => ['type' => TabularForm::INPUT_HIDDEN, 'visible' => false],
        'city_description' => ['type' => TabularForm::INPUT_TEXT],
        'city_code' => ['type' => TabularForm::INPUT_TEXT],
        'del' => [
            'type' => 'raw',
            'label' => '',
            'value' => function($model, $key) {
                return Html::a('<i class="glyphicon glyphicon-trash"></i>', '#', ['title' =>  Yii::t('app', 'Delete'), 'onClick' => 'delRowCities(' . $key . '); return false;', 'id' => 'cities-del-btn']);
            },
        ],
    ],
```
new city id's get generated when the _formCities in the views/region is like the above
but if you change visible=>true then it works as expected, So i suspect that visible=>false truncates the id on passing the data to the model so new id gets generated.. 
if you use it like this :
```php
echo TabularForm::widget([
    'dataProvider' => $dataProvider,
    'formName' => 'Cities',
    'checkboxColumn' => false,
    'actionColumn' => false,
    'attributeDefaults' => [
        'type' => TabularForm::INPUT_TEXT,
    ],
    'attributes' => [
        "city_id" => ['type' => TabularForm::INPUT_HIDDEN, 'visible' => true],
        'city_description' => ['type' => TabularForm::INPUT_TEXT],
        'city_code' => ['type' => TabularForm::INPUT_TEXT],
        'del' => [
            'type' => 'raw',
            'label' => '',
            'value' => function($model, $key) {
                return Html::a('<i class="glyphicon glyphicon-trash"></i>', '#', ['title' =>  Yii::t('app', 'Delete'), 'onClick' => 'delRowCities(' . $key . '); return false;', 'id' => 'cities-del-btn']);
            },
        ],
    ],
```
it seems to work as expected .Little crazy though..

**Comment by gvasilopulos** [comment] 2016-12-05 16:49
I Believe this can be fixed by changing crud/Generator.php on lines 668
            return "\"$attribute\" => ['type' => TabularForm::INPUT_HIDDEN, 'visible' => false]"; 
to this. I think INPUT_HIDDEN covers the issue of visibility too
            return "\"$attribute\" => ['type' => TabularForm::INPUT_HIDDEN
  and 680
            return "'$attribute' => ['type' => TabularForm::INPUT_HIDDEN, 'visible' => false]";
            return "'$attribute' => ['type' => TabularForm::INPUT_HIDDEN]";

**Comment by mootensai** [comment] 2016-12-06 01:43
Would you like to create a pull request?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: gvasilopulosSent: Senin, 5 Desember 2016 23.49To: mootensai/yii2-enhanced-giiReply To: mootensai/yii2-enhanced-giiSubject: Re: [mootensai/yii2-enhanced-gii] Bug on Gii in form update related model - action update is deleting the default keys (#91)I Believe this can be fixed by changing crud/Generator.php on lines 668
return ""$attribute" => ['type' => TabularForm::INPUT_HIDDEN, 'visible' => false]";
to this. I think INPUT_HIDDEN covers the issue of visibility too
return ""$attribute" => ['type' => TabularForm::INPUT_HIDDEN
and 680
return "'$attribute' => ['type' => TabularForm::INPUT_HIDDEN, 'visible' => false]";
return "'$attribute' => ['type' => TabularForm::INPUT_HIDDEN]";

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mootensai/yii2-enhanced-gii","title":"mootensai/yii2-enhanced-gii","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mootensai/yii2-enhanced-gii"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gvasilopulos in #91: I Believe this can be fixed by changing crud/Generator.php on lines 668\r\n            return \"\\\"$attribute\\\" =\u003e ['type' =\u003e TabularForm::INPUT_HIDDEN, 'visible' =\u003e false]\"; \r\nto this. I think INPUT_HIDDEN covers the issue of visibility too\r\n            return \"\\\"$attribute\\\" =\u003e ['type' =\u003e TabularForm::INPUT_HIDDEN\r\n  and 680\r\n            return \"'$attribute' =\u003e ['type' =\u003e TabularForm::INPUT_HIDDEN, 'visible' =\u003e false]\";\r\n            return \"'$attribute' =\u003e ['type' =\u003e TabularForm::INPUT_HIDDEN]\";"}],"action":{"name":"View Issue","url":"https://github.com/mootensai/yii2-enhanced-gii/issues/91#issuecomment-264907468"}}}

**Comment by gvasilopulos** [comment] 2016-12-06 21:08
I have made a pull request . I also have created a fork to cover my projects specific needs to use postgres with php generated uuid's and changed some other things to match my specific project needs. You can check it out if you like somethings might be useful in a more generic sense. https://github.com/gvasilopulos/yii2-enhanced-gii

**Comment by mootensai** [comment] 2016-12-08 04:27
I dont see any pull request 

![image](https://cloud.githubusercontent.com/assets/5844149/20997556/40b245de-bd39-11e6-8f13-ab5e6dedb6a1.png)

**Comment by alvarolordelo** [comment] 2016-12-08 11:28
Well the update action was performing bad in all situations when those
tables are related to others as fk.

**Comment by mootensai** [comment] 2017-02-07 05:15
Hi! Sorry for the delay..

Could you give me an sql dump? because it works fine with my basic sql here 
```
-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.1.10-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win32
-- HeidiSQL Version:             9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for relation-trait
CREATE DATABASE IF NOT EXISTS `relation-trait` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `relation-trait`;


-- Dumping structure for table relation-trait.agent
CREATE TABLE IF NOT EXISTS `agent` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `name` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  KEY `a_user_fk` (`user_id`),
  CONSTRAINT `a_user_fk` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;

-- Dumping data for table relation-trait.agent: ~6 rows (approximately)
/*!40000 ALTER TABLE `agent` DISABLE KEYS */;
INSERT IGNORE INTO `agent` (`id`, `user_id`, `name`) VALUES
	(3, 7, 'asdf'),
	(4, 10, 'yy'),
	(6, 11, 'zxcv'),
	(7, 12, 'yoyo'),
	(8, 16, 'qqq'),
	(9, 17, 'www'),
	(10, 1, 'asdf');
/*!40000 ALTER TABLE `agent` ENABLE KEYS */;


-- Dumping structure for table relation-trait.children
CREATE TABLE IF NOT EXISTS `children` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `father_id` int(11) NOT NULL DEFAULT '0',
  `value` varchar(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `FK_children_father` (`father_id`),
  CONSTRAINT `FK_children_father` FOREIGN KEY (`father_id`) REFERENCES `father` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

-- Dumping data for table relation-trait.children: ~2 rows (approximately)
/*!40000 ALTER TABLE `children` DISABLE KEYS */;
INSERT IGNORE INTO `children` (`id`, `father_id`, `value`) VALUES
	(3, 18, 'asdf'),
	(4, 18, 'zxcv'),
	(5, 22, 'tesNew1'),
	(6, 22, 'tesNew2'),
	(8, 22, 'tesNew3');
/*!40000 ALTER TABLE `children` ENABLE KEYS */;


-- Dumping structure for table relation-trait.father
CREATE TABLE IF NOT EXISTS `father` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1;

-- Dumping data for table relation-trait.father: ~1 rows (approximately)
/*!40000 ALTER TABLE `father` DISABLE KEYS */;
INSERT IGNORE INTO `father` (`id`, `name`) VALUES
	(17, 'asdf'),
	(18, 'qwerty'),
	(19, 'tes2017-update'),
	(22, 'tes2017-New');
/*!40000 ALTER TABLE `father` ENABLE KEYS */;


-- Dumping structure for table relation-trait.migration
CREATE TABLE IF NOT EXISTS `migration` (
  `version` varchar(180) NOT NULL,
  `apply_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table relation-trait.migration: ~2 rows (approximately)
/*!40000 ALTER TABLE `migration` DISABLE KEYS */;
INSERT IGNORE INTO `migration` (`version`, `apply_time`) VALUES
	('m000000_000000_base', 1465201030),
	('m130524_201442_init', 1465201046);
/*!40000 ALTER TABLE `migration` ENABLE KEYS */;


-- Dumping structure for table relation-trait.nested
CREATE TABLE IF NOT EXISTS `nested` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `root` int(11) DEFAULT NULL,
  `lft` int(11) NOT NULL,
  `rgt` int(11) NOT NULL,
  `lvl` smallint(5) NOT NULL,
  `name` varchar(60) NOT NULL,
  `icon` varchar(255) DEFAULT NULL,
  `icon_type` tinyint(1) NOT NULL DEFAULT '1',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `selected` tinyint(1) NOT NULL DEFAULT '0',
  `disabled` tinyint(1) NOT NULL DEFAULT '0',
  `readonly` tinyint(1) NOT NULL DEFAULT '0',
  `visible` tinyint(1) NOT NULL DEFAULT '1',
  `collapsed` tinyint(1) NOT NULL DEFAULT '0',
  `movable_u` tinyint(1) NOT NULL DEFAULT '1',
  `movable_d` tinyint(1) NOT NULL DEFAULT '1',
  `movable_l` tinyint(1) NOT NULL DEFAULT '1',
  `movable_r` tinyint(1) NOT NULL DEFAULT '1',
  `removable` tinyint(1) NOT NULL DEFAULT '1',
  `removable_all` tinyint(1) NOT NULL DEFAULT '0',
  `value1` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `tbl_product_NK1` (`root`),
  KEY `tbl_product_NK2` (`lft`),
  KEY `tbl_product_NK3` (`rgt`),
  KEY `tbl_product_NK4` (`lvl`),
  KEY `tbl_product_NK5` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- Dumping data for table relation-trait.nested: ~2 rows (approximately)
/*!40000 ALTER TABLE `nested` DISABLE KEYS */;
INSERT IGNORE INTO `nested` (`id`, `root`, `lft`, `rgt`, `lvl`, `name`, `icon`, `icon_type`, `active`, `selected`, `disabled`, `readonly`, `visible`, `collapsed`, `movable_u`, `movable_d`, `movable_l`, `movable_r`, `removable`, `removable_all`, `value1`) VALUES
	(1, 1, 1, 2, 0, 'asdf', '', 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 'asdf'),
	(2, 2, 1, 2, 0, 'qwerty', 'glyphicon glyphicon-pencil', 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 'asdfy');
/*!40000 ALTER TABLE `nested` ENABLE KEYS */;


-- Dumping structure for table relation-trait.profile
CREATE TABLE IF NOT EXISTS `profile` (
  `user_id` int(11) NOT NULL,
  `name` varchar(50) DEFAULT NULL,
  `address` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `FK__user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table relation-trait.profile: ~2 rows (approximately)
/*!40000 ALTER TABLE `profile` DISABLE KEYS */;
INSERT IGNORE INTO `profile` (`user_id`, `name`, `address`) VALUES
	(11, 'asdf', 'asdf'),
	(16, 'qqq', 'qqq'),
	(17, 'www', 'www');
/*!40000 ALTER TABLE `profile` ENABLE KEYS */;


-- Dumping structure for table relation-trait.table1
CREATE TABLE IF NOT EXISTS `table1` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `value` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- Dumping data for table relation-trait.table1: ~0 rows (approximately)
/*!40000 ALTER TABLE `table1` DISABLE KEYS */;
INSERT IGNORE INTO `table1` (`id`, `value`) VALUES
	(1, 'asdf');
/*!40000 ALTER TABLE `table1` ENABLE KEYS */;


-- Dumping structure for table relation-trait.table2
CREATE TABLE IF NOT EXISTS `table2` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `value` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- Dumping data for table relation-trait.table2: ~0 rows (approximately)
/*!40000 ALTER TABLE `table2` DISABLE KEYS */;
INSERT IGNORE INTO `table2` (`id`, `value`) VALUES
	(1, 'zxcv');
/*!40000 ALTER TABLE `table2` ENABLE KEYS */;


-- Dumping structure for table relation-trait.test
CREATE TABLE IF NOT EXISTS `test` (
  `table1id` bigint(20) NOT NULL,
  `table2id` bigint(20) NOT NULL,
  `field1` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`table1id`,`table2id`),
  KEY `key1_id_fk` (`table1id`),
  KEY `key2_id_fk` (`table2id`),
  CONSTRAINT `key1_id_fk` FOREIGN KEY (`table1id`) REFERENCES `table1` (`id`),
  CONSTRAINT `key2_id_fk` FOREIGN KEY (`table2id`) REFERENCES `table2` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table relation-trait.test: ~0 rows (approximately)
/*!40000 ALTER TABLE `test` DISABLE KEYS */;
INSERT IGNORE INTO `test` (`table1id`, `table2id`, `field1`) VALUES
	(1, 1, 127);
/*!40000 ALTER TABLE `test` ENABLE KEYS */;


-- Dumping structure for table relation-trait.user
CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `auth_key` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password_reset_token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` smallint(6) NOT NULL DEFAULT '10',
  `created_at` int(11) NOT NULL DEFAULT '0',
  `updated_at` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `password_reset_token` (`password_reset_token`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Dumping data for table relation-trait.user: ~7 rows (approximately)
/*!40000 ALTER TABLE `user` DISABLE KEYS */;
INSERT IGNORE INTO `user` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `email`, `status`, `created_at`, `updated_at`) VALUES
	(1, 'admin', 'VaLImwq4PUxUy6dbwhEZDmLRtR2vgZS_', '$2y$13$ziq69GKEJez3WCARTvWhOeqNofA8BJwAt8rNkQbuyzEQVJdf4IcqW', 'IOhz3gWfEa2uuBhXq00svhkp_Rmae3NG_1465203477', 'moo.tensai@gmail.com', 10, 1465203459, 1465203477),
	(7, 'asdf', 'asdf', 'asdf', 'asdf', 'asdf', 1, 2147483647, 2147483647),
	(9, 'qwer', 'qwer', 'qwer', 'qwer', 'qwer', 1, 2147483647, 2147483647),
	(10, 'yy', 'yy', 'yy', 'yy', 'yy', 1, 0, 0),
	(11, 'zxcv', 'zxcv', 'zxcv', 'zxcv', 'zxcv', 1, 0, 0),
	(12, 'yyyy1', 'yyyy1', 'yyyy1', 'yyyy1', 'yyyy1', 1, 0, 0),
	(16, 'qqq', 'qqq', 'qqq', 'qqq', 'qqq', 1, 0, 0),
	(17, 'www', 'www', 'www', 'www', 'www', 1, 0, 0);
/*!40000 ALTER TABLE `user` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
```

**Comment by mootensai** [comment] 2017-02-09 02:29
OK, I get it.. the problem is on mootensai/yii2-relation-trait

I'll think a way to fix that..

**Comment by mootensai** [comment] 2017-02-09 06:55
This is how i fix it 
```
'id' => [
            'type' => 'raw',
            'label' => '',
            'value' => function($model, $key) {
                return Html::hiddenInput('Children['.$key.'][id]', $model['id']);
            },
        ],
```

This is the result 
![image](https://cloud.githubusercontent.com/assets/5844149/22772469/7072ebb2-eecf-11e6-810f-c88afbe3d5e7.png)

OK?

**Comment by naduvko** [comment] 2017-02-15 07:16
CRUD generation is  using saveAll() in update action. And saveAll() deletes all related records. I can't understand why this is desired behavior? When I update AR, the PK remains the same. Why delete related then?

**Comment by mootensai** [comment] 2017-02-15 12:21
you need to show the ID column for that.. I'll fix it when I have time..

**Closed as completed** 2017-02-18 04:21 UTC

**Comment by mootensai** [comment] 2017-02-18 04:56
Thanks for reporting this bug everyone!!!
