### ISSUE TITLE
View loading error when a table contains relation and some data

### ISSUE THREAD

**Issue by RGTimothy** [mootensai/yii2-enhanced-gii#45] opened 2016-02-24 10:26 UTC
I'm using the package with the details as image below:

![mo](https://cloud.githubusercontent.com/assets/3026828/13282312/ed9ecb7a-db1a-11e5-877f-18a0f0ebdc3b.PNG)

So, in case I have 2 tables with the structures as below:

```
===============
|   table_a        
===============
|   id                        
|  description          
===============
```

And table_b with 1 foreign key refer to table_a

```
===============
|   table_b        
===============
|   table_a_id          
|  description          
===============
```

At first, it has no error when the table_a & table_b have no data. But then when these tables have some data, I cannot open the index & view. So much issues since then. You might want to try it.

**Comment by mootensai** [comment] 2016-02-24 10:29
Can you show me the error?

**Comment by RGTimothy** [comment] 2016-02-24 10:41
These 2 images below are the error.

![moo1](https://cloud.githubusercontent.com/assets/3026828/13282866/a7afe7cc-db1d-11e5-9dc3-5a35c90267d8.PNG)

![moo2](https://cloud.githubusercontent.com/assets/3026828/13282877/ae576fbe-db1d-11e5-8bc2-b44113b0c1d7.PNG)

**Comment by mootensai** [comment] 2016-02-25 03:18
Please show me the full error, generated models, & SQLs..

**Comment by mootensai** [comment] 2016-02-25 09:47
this is because you don't setup the foreign key of `table_a_id column` at `table_b`

**Comment by iurijacob** [comment] 2016-02-27 18:20
I'm having the same issue. This occurs when your tables have composite names, like my_table1.
So, for example, in `crud\Generator.php` in method `generateGridViewFieldIndex`, about line 941 you have:

``` php
$modelRel = $rel[2] ? Inflector::pluralize($rel[3]) : $rel[3];
$output = "[
    'attribute' => '$attribute',
    'label' => " . $this->generateString(ucwords(Inflector::humanize($rel[5]))) . ",
    'value' => function(\$model){
        return \$model->$modelRel->$labelCol;
    },
    'filterType' => GridView::FILTER_SELECT2,
    'filter' => \\yii\\helpers\\ArrayHelper::map(\\$this->nsModel\\$rel[1]::find()->asArray()->all(), '$rel[4]', '$labelCol'),
    'filterWidgetOptions' => [
        'pluginOptions' => ['allowClear' => true],
    ],
    'filterInputOptions' => ['placeholder' => '$humanize', 'id' => '$id']
],\n";
return $output;
```

Note that `$modeRel`at line 941 is set to pluralize or the normal attribute pattern (with underscore separating words). But at line 946 it should be in variablize pattern (with camelcase separating words).

In the case above we can fix the issue by changing the line 946 to:

``` php
$modelRel = $rel[2] ? Inflector::pluralize($rel[3]) : Inflector::variablize($rel[3]);
```

The same can be done in `generateDetailViewField` method, about line 826, that get fixed by replacing these lines:

``` php
$output = "[
'attribute' => '$rel[3].$labelCol',
'label' => " . $this->generateString(ucwords(Inflector::humanize($rel[5]))) . ",
```

with  these lines:

``` php
$modelRel = $rel[2] ? Inflector::pluralize($rel[3]) : Inflector::variablize($rel[3]);
$output = "[
'attribute' => '$modelRel.$labelCol',
'label' => " . $this->generateString(ucwords(Inflector::humanize($rel[5]))) . ",
```

I'm testing it by now, but it seems that the issue is cleared.

**Comment by mootensai** [comment] 2016-02-27 18:32
```
                                                                                  Please test @dev version‎. Is dev version is still generate the same error?
```

**Comment by iurijacob** [comment] 2016-02-27 19:03
Yes. I'm using the @dev version.

**Comment by mootensai** [comment] 2016-02-27 19:05
Sorry, I don't quite get it.. Is it still error when u use @dev version?

**Comment by iurijacob** [comment] 2016-02-27 19:45
Yes, the error still occurs in @dev version. You have to fix the code mentioned above in order to fix the issue.

**Comment by mootensai** [comment] 2016-02-29 02:09
could you give me your sqldump? I've tested @dev version with [http://downloads.mysql.com/docs/sakila-db.zip](sakila) database. And when I generate actors, film-actors, and films (many-many relationship / film-actors have composite pk), it's fine.

**Closed as completed** 2016-02-29 02:35 UTC

**Comment by iurijacob** [comment] 2016-02-29 14:22
Great!! it seems to be working now. 
Although it still stucks in self-referenced tables. But everything else is just fine.

**Comment by mootensai** [comment] 2016-02-29 15:35
Yes! For self reference table I'm trying to build nested builder.. it's on
https://github.com/mootensai/yii2-enhanced-gii-nested but it's unfinished
