### ISSUE TITLE
Relations Problem

### ISSUE THREAD

**Issue by mario0204** [mootensai/yii2-enhanced-gii#53] opened 2016-03-03 22:49 UTC
Hi, i'am always getting the following error:
¨Please fix the following errors: Data can't be deleted because it's still used by another data.¨
when i'm trying to insert or update data. I have the foreign key relations established correctly on my db. What could be the problem?
sorry if its a dumb question i'am still new to yii2.

**Comment by mootensai** [comment] 2016-03-04 01:52
Duplicate #43 

please update to the newest version..

type `composer update` on your terminal / command prompt on your project folder

if that doesn't work, type

```
composer remove mootensai/yii2-enhanced-gii
composer require mootensai/yii2-enhanced-gii:@dev
```

**Comment by mario0204** [comment] 2016-03-05 02:44
Thanks friend, everything is working fine after i updated enhanced-gii and yii2-relation-trait except everytime i update a record the related children get deleted.

**Comment by mootensai** [comment] 2016-03-05 04:46
What database are you using? It's not happening to me.

**Comment by mario0204** [comment] 2016-03-05 05:03
I'am using mysql

**Comment by mootensai** [comment] 2016-03-05 05:14
That's because you use the UUID column. empty the UUID Column field and it wont insert UUID.

What about the related children? Is it still deleted? I can't reproduce this issue

**Comment by mario0204** [comment] 2016-03-05 05:27
Yes the related children are still being deleted. The restrictions on my FK i have set update and delete to restrict.

**Comment by mootensai** [comment] 2016-03-05 05:42
I've also use restrict on update & delete.  And on update cascade. But it don't happen on my local

**Comment by mario0204** [comment] 2016-03-06 05:01
I deleted this code on relationtrait.php i don't know if it'll create an impact later on. Everything seems to be working fine.

"if($rel['ismultiple']){
                                        foreach ($rel['link'] as $k => $v) {
                                            $condition[] = $k . " = " . $this->$v;
                                        }
                                        try {
                                            $relModel->deleteAll(implode(" AND ", $condition));
                                        } catch (\yii\db\IntegrityException $exc) {
                                            $this->addError($rel['name'], "Data can't be deleted because it's still used by another data.");
                                            $error = true;
                                        }
                                    }"

**Comment by mootensai** [comment] 2016-03-07 02:04
I wouldn't recommend that.

Does anyone having this issue?

**Comment by mootensai** [comment] 2016-03-07 06:15
could you give me your sqldump?

**Comment by mario0204** [comment] 2016-03-07 16:44
https://drive.google.com/open?id=0B1VejtZzjoN1WjFRejFWcEZOdG8

**Comment by arjenmeijer** [comment] 2016-03-07 21:15
Yes, I have the problem too.

**Comment by arjenmeijer** [comment] 2016-03-08 07:44
I noticed that the stand alone trait development version uses a different trait version than the one in GII IO. Is that correct? Is it by design?

**Comment by mootensai** [comment] 2016-03-14 04:27
@arjenmeijer  
No. The relation trait version should be the same version as the enhanced gii version..

@mario0204 
could you send the screenshot of 

```
composer show -i
```

run that on your app folder

**Comment by mario0204** [comment] 2016-03-14 14:07
![captura](https://cloud.githubusercontent.com/assets/16679829/13747114/48d2624a-e9bc-11e5-927a-24cf33993a7f.PNG)

**Comment by mootensai** [comment] 2016-03-23 08:15
could you give me an sqldump with load of data?

**Comment by gaakoum** [comment] 2016-03-24 16:07
Hi, there. Exactly the same problem appeared with my database, and I traced the exception on line 151 of https://github.com/mootensai/yii2-relation-trait/blob/master/RelationTrait.php#L151
Upon closer inspection there appears to be a deleteAll called twice (one outside at line 147 and one inside the try block at line 149). This propably is not correct!

**Comment by gaakoum** [comment] 2016-03-24 23:58
Ok, I was wrong: the error "Data can't be deleted because it's still used by another data." was on https://github.com/mootensai/yii2-relation-trait/blob/master/RelationTrait.php#L191
But at least I replicated the problem mario0204 has.

My schema is like this:
[player]-->[comment]<--[comment_game]-->[game]
So a player can make many comments but each comment belongs to only one player.
Then each comment has a many-many relation with a game (so each comment may refer to many games and each game may belong to many comments)
I couldn't update the name of a player without getting the dreaded "Data can't be deleted because it's still used by another data."
It turns out this was because each time I updated a player there was an attempt to delete all the comments made by that player (and since some comments where connected to games it couldn't).
Indeed with this simple scheme:

CREATE TABLE IF NOT EXISTS `mydb`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `body` TEXT NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_player1_idx` (`player_id` ASC),
  CONSTRAINT `fk_comment_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `mydb`.`player` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB

and with these values:
INSERT INTO `mydb`.`player` (`id`, `username`, `email`) VALUES ('1', 'Johnu', 'john@in.gr');
INSERT INTO `mydb`.`player` (`id`, `username`, `email`) VALUES ('2', 'George ', 'george@gmail.com');
INSERT INTO `mydb`.`player` (`id`, `username`, `email`) VALUES ('3', 'Mike  f', 'michael@yahoo.com');

INSERT INTO `mydb`.`comment` (`id`, `title`, `body`, `player_id`) VALUES ('14', 'test 1', 'blah blah', '2');
INSERT INTO `mydb`.`comment` (`id`, `title`, `body`, `player_id`) VALUES ('15', 'test 2', 'frefg reg erg', '2');
INSERT INTO `mydb`.`comment` (`id`, `title`, `body`, `player_id`) VALUES ('16', 'test 3', 'ret ert er t', '3');

As soon as I update George all its comments are deleted.

What's the use of calling deleteAll when a record is only updated (!$isNewRecord) ?
Thanks a lot for your work, George

**Comment by mootensai** [comment] 2016-03-25 00:53
```
                                                                                  How to reproduce this error? I can't seem to reproduce this error..on what condition, what data is being deleted? Could you give me sqldump that contains some data to check with?
```

**Comment by mootensai** [comment] 2016-03-26 03:18
I've checked it. And that's because your data is being used on another table. Please re-check your data & table structure.

I'll close this issue for now until i can confirm this issue as a bug.

**Closed as completed by mootensai** 2016-03-26 03:18 UTC

**Comment by arjenmeijer** [comment] 2016-03-26 11:33
@mootensai: Can you give a hint what is going wrong. What is "your data is being used on another table" exactly?

**Comment by mootensai** [comment] 2016-03-26 12:29
```
                                                                                  That's because your data is being used as foreign key on another table. If I don't use that exception, it will give a database error. (I forgot what unhandled exception for that)
```
